### ISSUE TITLE
[BUG]: Player reconnect on voiceStateUpdate

### ISSUE THREAD

**Issue by ZuherLaith** [PerformanC/NodeLink#49] opened 2024-04-07 22:37 UTC
### NodeLink version

2.0.1

### Description

Currently NL isn't reconnecting when voiceStateUpdate of the player is changed, which basically destroy's the player when player is moved from channel to channel in discord.

### Client

FL 2.4.2

### Steps to reproduce

Request something on your client, then move the bot to another channel, player will stop sending audio after that until a new player is created.

### Confirmations

- [X] My environment meets the minimum requirements.
- [X] I have verified that this is not a duplicate issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnschooledGamer** [comment] 2024-04-08 10:06
Hi @ZuherLaith ,

I have informed Pedro he'll soon look into this.

I have successfully reproduced the Bug.
Marking it as **confirmed**.

_Thanks,
UG._

**Comment by ThePedroo** [comment] 2024-04-13 00:14
This will be patched with a small commit in NodeLink side, but mostly in `@performanc/voice` part. This issue is also caused by FastLink, I'll give more information once all gets solved.

**Comment by ThePedroo** [comment] 2024-04-13 00:48
https://github.com/PerformanC/voice/commit/a779648cb7ce0d7c114369fcb4cbde6a80c880e6, https://github.com/PerformanC/FastLink/commit/f4f7ac5cc4c40789b8d5a54a2f8eb66aa83e91c1 and https://github.com/PerformanC/NodeLink/commit/a61fde4cc4559e7577aec3188d47369a47bcdadc seems to fix the issue. Can anyone else confirm this?

**Comment by UnschooledGamer** [comment] 2024-04-13 02:06
> [PerformanC/voice@a779648](https://github.com/PerformanC/voice/commit/a779648cb7ce0d7c114369fcb4cbde6a80c880e6), [PerformanC/FastLink@f4f7ac5](https://github.com/PerformanC/FastLink/commit/f4f7ac5cc4c40789b8d5a54a2f8eb66aa83e91c1) and [a61fde4](https://github.com/PerformanC/NodeLink/commit/a61fde4cc4559e7577aec3188d47369a47bcdadc) seems to fix the issue. Can anyone else confirm this?

I'll test out later on

**Comment by UnschooledGamer** [comment] 2024-04-13 06:42
> > [PerformanC/voice@a779648](https://github.com/PerformanC/voice/commit/a779648cb7ce0d7c114369fcb4cbde6a80c880e6), [PerformanC/FastLink@f4f7ac5](https://github.com/PerformanC/FastLink/commit/f4f7ac5cc4c40789b8d5a54a2f8eb66aa83e91c1) and [a61fde4](https://github.com/PerformanC/NodeLink/commit/a61fde4cc4559e7577aec3188d47369a47bcdadc) seems to fix the issue. Can anyone else confirm this?
> 
> I'll test out later on

It works Great. But can restore the `position` too(like not restart the song back from 0)? Something like saving the previous position, Then seeking it to back to original position back after reconnection/moved

**Comment by UnschooledGamer** [comment] 2024-04-13 12:50
> 🤔 I completely missed that one. Will work on it!

Alright, Good Job.

**Comment by ThePedroo** [comment] 2024-04-13 13:24
https://github.com/PerformanC/voice/compare/7271ef71eabd...c84b01d48d4a, https://github.com/PerformanC/NodeLink/commit/45f71ee4257cb71b06e969cff30350ceea6b417e and https://github.com/PerformanC/voice/commit/7271ef71eabde87584c73df80cb0b6777045ea0a should fix bugs related to this issue and this issue itself. Can anyone confirm?

**Comment by ThePedroo** [comment] 2024-04-13 16:20
Tested on Discord.

**Closed by ThePedroo** 2024-04-13 16:20 UTC
Labels: bug, confirmed
